export const cakeData = {
  cakes: [
    {
      id: 1,
      img: "cake1.jpg",
      title: "Strawberry Cake",
      price: 200,
      filling: ["strawberry"],
      category: ["birthday", "anniversary"],
      allergens: ["gluten", "nuts", "dairy"],
      description:
        "Delicious free strawberry base cake with lots of customization options!",
    },
    {
      id: 2,
      img: "cake2.jpg",
      title: "Dairy-free Chocolate Cake",
      price: 300,
      filling: ["chocolate"],
      category: ["birthday"],
      allergens: ["gluten", "nuts"],
      description:
        "Delicious dairy-free chocolate base cake with lots of customization options!",
    },
    {
      id: 3,
      img: "cake3.jpg",
      title: "Gluten-free Vanilla Cake",
      price: 400,
      filling: ["vanilla"],
      category: ["birthday", "anniversary"],
      allergens: ["dairy"],
      description:
      "Delicious vanilla base cake with lots of customization options!",
    },
    {
      id: 4,
      img: "cake4.jpg",
      title: "Gluten-free Chocolate Cake",
      price: 200,
      filling: ["chocolate"],
      category: ["birthday", "anniversary"],
      allergens: ["nuts"],
      description:
        "Delicious gluten-free chocolate base cake with lots of customization options!",
    },
    {
      id: 5,
      img: "cake5.jpg",
      title: "Chocolate Cake",
      price: 300,
      filling: ["chocolate"],
      category: ["birthday"],
      allergens: ["gluten"],
      description:
      "Delicious chocolate base cake with lots of customization options!",
    },
    {
      id: 6,
      img: "cake6.jpg",
      title: "Vanilla Cake",
      price: 100,
      filling: ["vanilla"],
      category: ["birthday"],
      allergens: ["gluten", "dairy"],
      description:
      "Delicious vanilla base cake with lots of customization options!",
    },
    {
      id: 7,
      img: "cake7.jpg",
      title: "Strawberry Cake",
      price: 200,
      filling: ["strawberry"],
      allergens: ["gluten"],
      category: ["birthday"],
      description:
        "Delicious strawberry base cake with lots of customization options!",
    },
    {
      id: 8,
      img: "cake8.jpg",
      title: "Chocolate Cake",
      price: 300,
      filling: ["chocolate"],
      category: ["birthday"],
      allergens: ["gluten", "nuts", "dairy"],
      description:
      "Delicious chocolate base cake with lots of customization options!",
    },
    {
      id: 9,
      img: "cake9.jpg",
      title: "Gluten-free Vanilla Cake",
      price: 200,
      filling: ["vanilla"],
      category: ["birthday"],
      allergens: ["dairy"],
      description:
      "Delicious vanilla base cake with lots of customization options!",
    },
    {
      id: 10,
      img: "cake10.jpg",
      title: "Gluten-free Vanilla Cake",
      price: 400,
      filling: ["vanilla"],
      category: ["birthday"],
      allergens: [],
      description:
      "Delicious gluten-free and dairy-free vanilla base cake with lots of customization options!",
    },
    {
      id: 11,
      img: "wedding1.jpg",
      title: "Vanilla Wedding Cake",
      price: 400,
      filling: ["vanilla"],
      category: ["wedding"],
      allergens: ["gluten", "dairy"],
      description:
      "Delicious vanilla wedding base cake with lots of customization options!",
    },
    {
      id: 12,
      img: "wedding2.jpg",
      title: "Chocolate Wedding Cake",
      price: 600,
      filling: ["chocolate"],
      category: ["wedding"],
      allergens: ["gluten", "nuts", "dairy"],
      description:
      "Delicious chocolate wedding base cake with lots of customization options!",
    },
    {
      id: 13,
      img: "wedding3.jpg",
      title: "Strawberry Wedding Cake",
      price: 500,
      filling: ["strawberry"],
      category: ["wedding"],
      allergens: ["dairy"],
      description:
        "Delicious strawberry wedding base cake with lots of customization options!",
    },
    {
      id: 14,
      img: "wedding5.jpg",
      title: "Strawberry Wedding Cake",
      price: 400,
      filling: ["strawberry"],
      category: ["wedding"],
      allergens: [],
      description:
        "Delicious strawberry wedding base cake with lots of customization options!",
    },
    {
      id: 15,
      img: "wedding4.jpg",
      title: "Chocolate Wedding Cake",
      price: 400,
      filling: ["chocolate"],
      category: ["wedding"],
      allergens: ["nuts", "dairy"],
      description:
      "Delicious chocolate wedding base cake with lots of customization options!",
    },
    {
      id: 16,
      img: "wedding6.jpg",
      title: "Vanilla Wedding Cake",
      price: 650,
      filling: ["vanilla"],
      category: ["wedding"],
      allergens: ["gluten", "nuts", "dairy"],
      description:
      "Delicious vanilla wedding base cake with lots of customization options!",
    },
  ],
};
